"""Read-only source inventory and citation checking for Codex-generated code maps.
This checks file/symbol/anchor/hash references, not business semantics or test correctness.
No project code is imported or executed. No maps are generated by guessing.
"""
from __future__ import annotations
import argparse
import ast
import hashlib
import json
from pathlib import Path
import re
import sys

ROLES = {'入口', '输入边界', '核心决策', '下游/状态', '测试'}
EXCLUDE = {'.git', '.venv', '__pycache__', '.local', 'node_modules', 'target', 'build'}
SUFFIXES = {'.py', '.java', '.sql', '.toml', '.xml', '.yaml', '.yml', '.properties'}

def local_file(project: Path, value: str) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise ValueError('path必须是项目内相对文件路径。')
    rel = Path(value)
    if rel.is_absolute() or '..' in rel.parts or '\\' in value or re.match(r'^[A-Za-z]:', value):
        raise ValueError('使用/分隔的相对路径，不能越界。')
    cur = project
    for part in rel.parts:
        cur /= part
        if cur.is_symlink():
            raise ValueError('路径包含符号链接。')
    p = cur.resolve()
    if not p.is_relative_to(project) or not p.is_file():
        raise ValueError('文件不存在或不属于当前项目。')
    if p.stat().st_size > 2_000_000:
        raise ValueError('引用文件超过2MB，请改用小型源码/配置。')
    return p

def python_symbols(text: str) -> list[dict]:
    out: list[dict] = []
    def visit(node: ast.AST, parents: list[str]) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                full = '.'.join(parents + [child.name])
                out.append({'name': child.name, 'qualified': full, 'line': child.lineno,
                            'end_line': child.end_lineno})
                visit(child, parents + [child.name])
            else:
                visit(child, parents)
    visit(ast.parse(text), [])
    return out

def inventory(project: Path) -> dict:
    project = project.resolve()
    if not project.is_dir(): raise ValueError('项目目录不存在。')
    rows = []
    for root in ['devagent', 'tests', 'evaluation', 'java-task-service/src']:
        base = project / root
        if not base.is_dir() or base.is_symlink(): continue
        for p in sorted(base.rglob('*')):
            rel = p.relative_to(project)
            if p.suffix not in SUFFIXES or any(x in EXCLUDE for x in rel.parts): continue
            if any(x in p.name.lower() for x in ['secret','credential','private-key']) or p.name.startswith('.env'): continue
            try:
                f = local_file(project, rel.as_posix())
                data = f.read_bytes(); text = data.decode('utf-8')
                row = {'path': rel.as_posix(), 'sha256': hashlib.sha256(data).hexdigest(), 'symbols': []}
                if p.suffix == '.py': row['symbols'] = python_symbols(text)
                rows.append(row)
            except (ValueError, OSError, UnicodeError, SyntaxError):
                continue
            if len(rows) >= 2000: return {'status':'partial','files':rows,'note':'上限2000个；这不是职责映射或正确性结论。'}
    return {'status': 'inventory_only', 'files': rows,
            'note': '只列真实文件与Python定义；没有推断它们满足哪项课程意图，不执行项目代码。'}

def validate(project: Path, mapping: Path) -> dict:
    project = project.resolve()
    mp = mapping if mapping.is_absolute() else project / mapping
    try:
        relative = mp.relative_to(project).as_posix()
    except ValueError as exc:
        raise ValueError('源码地图必须是当前项目内已存在的JSON文件。') from exc
    mp = local_file(project, relative)
    raw = json.loads(mp.read_text(encoding='utf-8'))
    if not isinstance(raw,dict): raise ValueError('源码地图顶层必须是JSON对象。')
    entries = raw.get('entries')
    if not isinstance(entries, list) or not entries: raise ValueError('entries必须是非空列表。')
    errors = []; unfinished = []; checked = []; observed_roles = set()
    lesson = raw.get('lesson')
    if not isinstance(lesson,str) or not re.fullmatch(r'(?:L\d{2}|F\d{2}|R\d{2}|J\d{2})', lesson): errors.append('无效lesson课号。')
    for i, e in enumerate(entries):
        try:
            if not isinstance(e, dict): raise ValueError('条目必须是对象。')
            state = e.get('status')
            if state in {'planned', 'missing'}:
                unfinished.append({'index': i, 'role': e.get('role'), 'status': state}); continue
            if state != 'observed': raise ValueError('status必须为observed/planned/missing。')
            role = e.get('role')
            if role not in ROLES: raise ValueError('未知role；使用入口/输入边界/核心决策/下游/状态/测试。')
            p = local_file(project, e.get('path'))
            data = p.read_bytes(); text = data.decode('utf-8')
            digest = hashlib.sha256(data).hexdigest()
            if e.get('sha256') != digest: raise ValueError('文件哈希不一致，地图可能过期。')
            anchor = e.get('anchor')
            if not isinstance(anchor, str) or len(anchor.strip()) < 4 or anchor not in text:
                raise ValueError('anchor不是该文件中至少4字符的原文。')
            symbol = e.get('symbol')
            if not isinstance(symbol, str) or not symbol.strip(): raise ValueError('缺少真实symbol或配置块名称。')
            if p.suffix == '.py':
                symbols = python_symbols(text)
                if not any(symbol in {s['name'], s['qualified']} for s in symbols):
                    # Module-level objects must be real assignment targets, not arbitrary text.
                    tree = ast.parse(text)
                    targets = set()
                    for n in tree.body:
                        if isinstance(n, ast.Assign):
                            for target in n.targets:
                                if isinstance(target, ast.Name): targets.add(target.id)
                        elif isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name): targets.add(n.target.id)
                    if symbol not in targets: raise ValueError('Python符号未在定义/模块级赋值中找到。')
            elif symbol not in text:
                raise ValueError('符号/配置键不在文件正文；非Python仅作文本定位检查。')
            observed_roles.add(role)
            checked.append({'role': role, 'path': e['path'], 'symbol': symbol, 'anchor_line': text[:text.index(anchor)].count('\n')+1})
        except (ValueError, OSError, UnicodeError, SyntaxError) as exc:
            errors.append({'index': i, 'error': str(exc)})
    missing_roles = sorted(ROLES - observed_roles)
    status = 'invalid' if errors else 'incomplete' if unfinished or missing_roles else 'references_valid'
    return {'status': status, 'lesson': lesson, 'checked': checked, 'unfinished': unfinished,
            'missing_roles': missing_roles, 'errors': errors,
            'scope': 'references_only_not_semantic_verification; map validity does not mean application or learning passed'}

def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest='command', required=True)
    a = sub.add_parser('inventory'); a.add_argument('--project', type=Path, default=Path('.'))
    a = sub.add_parser('validate'); a.add_argument('--project', type=Path, default=Path('.'));a.add_argument('--map', type=Path, required=True)
    args = p.parse_args()
    try:
        result = inventory(args.project) if args.command == 'inventory' else validate(args.project, args.map)
    except (ValueError, OSError, json.JSONDecodeError) as exc:
        print(json.dumps({'status':'blocked','error':str(exc)}, ensure_ascii=False));return 2
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result['status'] in {'inventory_only','references_valid'} else 2

if __name__ == '__main__':
    raise SystemExit(main())
